"""Visual theme constants: colours, spacing, button variant names."""

from __future__ import annotations

THEME = {
    "bg": "#f7f8fc",
    "bg_alt": "#edf0f8",
    "card": "#ffffff",
    "shadow": "#d4daea",
    "text": "#0d0d1a",
    "muted": "#5a6482",
    "accent": "#5b5bd6",
    "accent_dark": "#4444b8",
    "secondary": "#7c3aed",
    "success": "#059669",
    "danger": "#dc2626",
    "border": "#dde2f0",
    "select": "#ede9fe",
    "hero": "#1a1040",
    "hero_mid": "#261550",
    "hero_text": "#eeeeff",
    "hero_muted": "#a5b4fc",
    "hero_stripe": "#6366f1",
    "hero_stripe_alt": "#7c3aed",
    "hero_stripe_hot": "#a855f7",
    "hero_stripe_dark": "#4f46e5",
    "white": "#ffffff",
    "button_hover": "#e0e4f8",
    "button_disabled": "#eaecf6",
    "primary_disabled": "#9b9bd4",
    "primary_disabled_text": "#e8e8f5",
    "secondary_hover": "#f0eeff",
    "secondary_disabled": "#f5f6fb",
    "secondary_disabled_text": "#9aa0be",
    "soft_primary": "#ebebff",
    "soft_primary_hover": "#ddddf8",
    "soft_primary_disabled": "#f0f0ff",
    "subtle": "#f4f5fb",
    "subtle_hover": "#e8eaf6",
    "placeholder_bg": "#f3f1ff",
    "placeholder_text": "#7b82aa",
    "canvas_grid": "#d8deeb",
    "disabled_outline": "#a8b0c2",
    "disabled_fill": "#e5e7ef",
    "status_error": "#b91c1c",
    "timestamp": "#7b8aa8",
}

DARK_THEME = {
    "bg": "#0f0f1a",
    "bg_alt": "#1a1a2e",
    "card": "#16213e",
    "shadow": "#0a0a14",
    "text": "#e8e8ff",
    "muted": "#8888cc",
    "accent": "#7c7cf0",
    "accent_dark": "#6060d0",
    "secondary": "#9d5cff",
    "success": "#059669",
    "danger": "#dc2626",
    "border": "#2a2a4a",
    "select": "#1e1e4a",
    "hero": "#06060f",
    "hero_mid": "#0d0d24",
    "hero_text": "#eeeeff",
    "hero_muted": "#8888cc",
    "hero_stripe": "#5b5bd6",
    "hero_stripe_alt": "#6b3acd",
    "hero_stripe_hot": "#9855e7",
    "hero_stripe_dark": "#4040c0",
    "white": "#e8e8ff",
    "button_hover": "#2a2a4a",
    "button_disabled": "#1a1a2e",
    "primary_disabled": "#5050a0",
    "primary_disabled_text": "#9090cc",
    "secondary_hover": "#1e1e3a",
    "secondary_disabled": "#1a1a2e",
    "secondary_disabled_text": "#5050a0",
    "soft_primary": "#1e1e3a",
    "soft_primary_hover": "#262650",
    "soft_primary_disabled": "#161628",
    "subtle": "#1a1a2e",
    "subtle_hover": "#222238",
    "placeholder_bg": "#12122a",
    "placeholder_text": "#5050a0",
    "canvas_grid": "#2a2a4a",
    "disabled_outline": "#3a3a5a",
    "disabled_fill": "#1a1a2e",
    "status_error": "#ef4444",
    "timestamp": "#6060a0",
}

SPACING = {
    "xs": 4,
    "sm": 8,
    "md": 16,
    "lg": 24,
    "xl": 32,
    "2xl": 48,
}

BUTTON_VARIANTS = {
    "primary": "Primary.TButton",
    "secondary": "Secondary.TButton",
    "soft": "SoftPrimary.TButton",
    "tertiary": "Subtle.TButton",
    "link": "Link.TButton",
}
